#! /bin/sh

# shellcheck disable=SC2034
this_script_desc="Build a shared object for a grammar"

this_script=$(readlink -f "$0")
this_script_dir=$(dirname "$this_script")
this_script_name=$(basename "$this_script")

# shellcheck source=.common
. "$this_script_dir/.common"

########################################################################

cur_dir=$(pwd)

deprintf "%s: start\n" "$this_script_name"

cd "$ATSP_LANG_ROOT" || exit 1

########################################################################

# ATSP_BUILD_DIR and ATSP_SO_NAME are necessary
cmd="make -f $ATSP_DATA/Makefile $ATSP_BUILD_DIR/$ATSP_SO_NAME"

deprintf "* Invoking:\n"
deprintf "    %s\n" "$cmd"

eval "$cmd"
result=$?

if [ 0 -ne "$result" ]; then
  eprintf "* Compiling failed: %s.\n" "$result"
  eprintf "%s: abort\n" "$this_script_name"
  exit 1
fi

deprintf "* Result is at:\n"
deprintf "    %s\n" "$ATSP_BUILD_DIR/$ATSP_SO_NAME"

########################################################################

cd "$cur_dir" || exit 1

deprintf "%s: end\n" "$this_script_name"
