#! /bin/sh

# shellcheck disable=SC2034
THIS_SCRIPT_DESC="Build a shared object for a grammar"

THIS_SCRIPT=$(readlink -f "$0")
THIS_SCRIPT_DIR=$(dirname "$THIS_SCRIPT")
THIS_SCRIPT_NAME=$(basename "$THIS_SCRIPT")

# shellcheck source=.common
. "$THIS_SCRIPT_DIR/.common"

dep_script="gen-src"

########################################################################

cur_dir=$(pwd)

deprintf "%s: start\n" "$THIS_SCRIPT_NAME"

cd "$PARSER_PROJ_DIR" || exit 1

########################################################################

# this section is all about prerequisites

do_dep=${ATSP_FORCE:-0}

# decide whether to execute dependency script
if [ 1 -eq "$do_dep" ]; then
  deprintf "* Unconditionally executing %s.\n" "$dep_script"
else
  deprintf "* Looking for parser source:\n"
  deprintf "    %s\n" "src/parser.c"

  if [ -f src/parser.c ]; then
    deprintf "* Found.\n"
  else
    deprintf "* Failed to find.\n"
    do_dep=1
  fi
fi

# executing dependency script if necessary
if [ 1 -eq "$do_dep" ]; then
  deprintf "* Calling %s.\n" "$dep_script"

  "$THIS_SCRIPT_DIR"/"$dep_script"
  result=$?

  if [ 0 -eq "$result" ]; then
    deprintf "%s: resume\n" "$THIS_SCRIPT_NAME"
  else
    eprintf "%s: abort\n" "$THIS_SCRIPT_NAME"
    exit 1
  fi
fi

########################################################################

# the rest of the file is about actually carrying things out

deprintf "* Ensuring build directory exists at:\n"

deprintf "    %s\n" "$BUILD_DIR_PATH"

mkdir -p "$BUILD_DIR_PATH"

so_name=$("$ATSP_UTIL"/so-name)

# XXX: not relying on the tree-sitter cli for building seems more
#      flexible.
#
#      on windows i had problems compiling using msys2 / mingw64 when
#      trying to use various tree-sitter subcommands.  to debug, i
#      ended up modifying the tree-sitter cli's source code to print
#      out precisely what the compiler invocation was.  that involved
#      writing some rust, recomplining the tree-sitter cli, and
#      running the invocation again.  that kind of thing seems like it
#      could be avoided by externalization as is dones below.
deprintf "* Compiling parser\n"

cmd="cc -fPIC -c -Isrc src/parser.c -o $BUILD_DIR_PATH/parser.o"

deprintf "* Invoking:\n"
deprintf "    %s\n" "$cmd"

eval "$cmd"
result=$?

if [ 0 -ne "$result" ]; then
  eprintf "* Compiling failed: %s.\n" "$result"
  eprintf "%s: abort\n" "$THIS_SCRIPT_NAME"
  exit 1
fi

has_scanner=0

if [ -f src/scanner.c ]; then
  cmd="cc -fPIC -c -Isrc src/scanner.c -o $BUILD_DIR_PATH/scanner.o"
  has_scanner=1
elif [ -f src/scanner.cc ]; then
  cmd="c++ -fPIC -Isrc -c src/scanner.cc -o $BUILD_DIR_PATH/scanner.o"
  has_scanner=1
fi

if [ 1 -eq "$has_scanner" ]; then
  deprintf "* Compiling scanner\n"

  deprintf "* Invoking:\n"
  deprintf "    %s\n" "$cmd"

  eval "$cmd"
  result=$?

  if [ 0 -ne "$result" ]; then
    eprintf "* Compiling failed: %s.\n" "$result"
    eprintf "%s: abort\n" "$THIS_SCRIPT_NAME"
    exit 1
  fi
fi

deprintf "* Linking\n"
if [ -f src/scanner.cc ]; then
  cmd="c++ -fPIC -shared $BUILD_DIR_PATH/*.o -o $BUILD_DIR_PATH/$so_name"
else
  cmd="cc -fPIC -shared $BUILD_DIR_PATH/*.o -o $BUILD_DIR_PATH/$so_name"
fi

deprintf "* Invoking:\n"
deprintf "    %s\n" "$cmd"

eval "$cmd"
result=$?

if [ 0 -ne "$result" ]; then
  eprintf "* Linking failed: %s.\n" "$result"
  eprintf "%s: abort\n" "$THIS_SCRIPT_NAME"
  exit 1
fi

deprintf "* Result is at:\n"
deprintf "    %s\n" "$BUILD_DIR_PATH/$so_name"

########################################################################

cd "$cur_dir" || exit 1

deprintf "%s: end\n" "$THIS_SCRIPT_NAME"
