#! /bin/sh

# shellcheck disable=SC2034
this_script_desc="Perform diagnostics and report"

this_script=$(readlink -f "$0")
this_script_dir=$(dirname "$this_script")
this_script_name=$(basename "$this_script")

# shellcheck source=.common
. "$this_script_dir/.common"

########################################################################

cur_dir=$(pwd)

deprintf "%s: start\n" "$this_script_name"

cd "$ATSP_LANG_ROOT" || exit 1

########################################################################

printf "\n"
printf "tree-sitter\n"
printf "\n"

if [ "" = "$ATSP_TS_PATH" ]; then
  printf "* ATSP_TS_PATH not set."
  exit 1
fi

# XXX: is this correct?
if [ ! -e "$(realpath "$ATSP_TS_PATH")" ] && \
   [ "" = "$(which "$ATSP_TS_PATH")" ]; then
  printf "* cli not found at: %s\n" "$ATSP_TS_PATH"
  exit 1
fi

printf "* Located binary\n"

printf "* ATSP_TS_PATH: %s\n" "$ATSP_TS_PATH"

# example tree-sitter --version output:
#
#   tree-sitter 0.20.7 (9ac55f79d191f6fa200b1894ddac449fa3df70c1)
#
#   1           2      3
#
# so split on spaces and take the 2nd and 3rd fields
printf "* version: %s\n" "$($ATSP_TS_PATH --version | cut -d' ' -f2)"
# also remove surrounding parens -- otherwise can interfere with things
printf "* commit: %s\n" "$($ATSP_TS_PATH --version | cut -d' ' -f3 | tr -d '()')"

########################################################################

printf "\n"
printf "emsdk\n"
printf "\n"

# try getting a value from conf file
emsdk=${ATSP_EMSDK_DIR:-"$("$ATSP_UTIL"/atsp-emsdk-dir)"}

# XXX: this is not using the same logic necessarily as other code so
#      its reliability is more in doubt than otherwise...

if [ "" = "$emsdk" ]; then
 eprintf "* Did not find an appropriate value for emsdk directory\n"
 eprintf "  * build-wasm and playground subcommands may not work\n"
 else
   if [ ! -d "$emsdk" ]; then
     eprintf "* emsdk value not a directory: %s\n" "$emsdk"
     eprintf "  * build-wasm and playground subcommands may not work\n"
   else
     emsdk=$(realpath "$emsdk")

     printf "* emsdk: %s\n" "$emsdk"

     printf "* Looks like an emsdk directory\n"

     # XXX: lame...
     #   https://emscripten.org/docs/tools_reference/emsdk.html#how-do-i-check-which-versions-of-the-sdk-and-tools-are-installed
     printf "* To find out the version installed, run:\n"

     printf "    ./emsdk list | grep INSTALLED\n"

     printf "  in:\n"

     printf "    %s\n" "$emsdk"
   fi
fi

########################################################################

printf "\n"
printf "Some TREE_SITTER_* environment variables\n"
printf "\n"

printf "* TREE_SITTER_DIR: %s\n" "$TREE_SITTER_DIR"

printf "* TREE_SITTER_LIBDIR: %s\n" "$TREE_SITTER_LIBDIR"

########################################################################

printf "\n"
printf "atsp's conf currently contains:\n"
printf "\n"

cat "$ATSP_CONF"

printf "\n"

########################################################################

cd "$cur_dir" || exit 1

deprintf "%s: end\n" "$this_script_name"
