#! /bin/sh

THIS_SCRIPT=$(readlink -f "$0")
THIS_SCRIPT_DIR=$(dirname "$THIS_SCRIPT")

# shellcheck source=.common
. "${THIS_SCRIPT_DIR}/.common"

########################################################################

cur_dir=$(pwd)

cd "${PARSER_PROJ_DIR}" || exit 1

if [ $# -eq 0 ]; then
  printf "Cleaning build directory\n"
fi

rm -rf "${BUILD_DIR_PATH}"

cd "${cur_dir}" || exit 1

if [ $# -eq 0 ]; then
  printf "Done\n"
fi

