#! /bin/sh

# shellcheck disable=SC2034
THIS_SCRIPT_DESC="Clean all built artifacts"

THIS_SCRIPT=$(readlink -f "$0")
THIS_SCRIPT_DIR=$(dirname "$THIS_SCRIPT")

# shellcheck source=.common
. "${THIS_SCRIPT_DIR}/.common"

########################################################################

cur_dir=$(pwd)

cd "${PARSER_PROJ_DIR}" || exit 1

deprintf "Working on cleaning various files.\n"

deprintf "\n"

deprintf "* Generated source\n"
"${THIS_SCRIPT_DIR}"/clean-gen-src 1

deprintf "* Build directory\n"
"${THIS_SCRIPT_DIR}"/clean-build-dir 1

deprintf "* Wasm file\n"
"${THIS_SCRIPT_DIR}"/clean-wasm-file 1

cd "${cur_dir}" || exit 1

deprintf "\n"

deprintf "Done\n"
