#! /bin/sh

THIS_SCRIPT=$(readlink -f "$0")
THIS_SCRIPT_DIR=$(dirname "$THIS_SCRIPT")

# shellcheck source=.common
. "${THIS_SCRIPT_DIR}/.common"

########################################################################

CUR_DIR=$(pwd)

cd "${PARSER_PROJ_DIR}" || exit 1

if [ $# -eq 0 ]; then
  printf "Cleaning generated source\n"
fi

rm -rf src/parser.c
rm -rf src/grammar.json src/node-types.json
rm -rf src/tree_sitter

cd "${CUR_DIR}" || exit 1

if [ $# -eq 0 ]; then
  printf "Done\n"
fi


