#! /bin/sh

# shellcheck disable=SC2034
this_script_desc="Clean all built artifacts"

this_script=$(readlink -f "$0")
this_script_dir=$(dirname "$this_script")
this_script_name=$(basename "$this_script")

# shellcheck source=.common
. "$this_script_dir/.common"

########################################################################

cur_dir=$(pwd)

deprintf "%s: start\n" "$this_script_name"

cd "$ATSP_LANG_ROOT" || exit 1

########################################################################

# XXX: not checking return values...

deprintf "* Generated source\n"

"$this_script_dir"/clean-gen-src

deprintf "* Build directory\n"

"$this_script_dir"/clean-build-dir

deprintf "* Wasm file\n"

"$this_script_dir"/clean-wasm-file

########################################################################

cd "$cur_dir" || exit 1

deprintf "%s: end\n" "$this_script_name"
