#! /bin/sh

THIS_SCRIPT=$(readlink -f "$0")
THIS_SCRIPT_DIR=$(dirname "$THIS_SCRIPT")
THIS_SCRIPT_NAME=$(basename "$THIS_SCRIPT")

# shellcheck source=.common
. "$THIS_SCRIPT_DIR/.common"

########################################################################

cur_dir=$(pwd)

deprintf "%s: start\n" "$THIS_SCRIPT_NAME"

cd "$PARSER_PROJ_DIR" || exit 1

########################################################################

cmd="rm -rf src/parser.c src/grammar.json src/node-types.json src/tree_sitter"

deprintf "* Invoking:\n"
deprintf "    %s\n" "$cmd"

eval "$cmd"
result=$?

if [ 0 -ne "$result" ]; then
  eprintf "* Cleaning failed: %s.\n" "$result"
  eprintf "%s: abort\n" "$THIS_SCRIPT_NAME"
  exit 1
fi

########################################################################

cd "$cur_dir" || exit 1

deprintf "%s: end\n" "$THIS_SCRIPT_NAME"



