#! /bin/sh

THIS_SCRIPT=$(readlink -f "$0")
THIS_SCRIPT_DIR=$(dirname "$THIS_SCRIPT")

# shellcheck source=.common
. "${THIS_SCRIPT_DIR}/.common"

########################################################################

cur_dir=$(pwd)

cd "${PARSER_PROJ_DIR}" || exit 1

if [ $# -eq 0 ]; then
  deprintf "Cleaning wasm file\n"
fi

parser_wasm=$("${ATSP_UTIL}"/wasm-name)

rm -f "${parser_wasm}"

cd "${cur_dir}" || exit 1

if [ $# -eq 0 ]; then
  deprintf "Done\n"
fi
