#! /bin/sh

# shellcheck disable=SC2034
this_script_desc="Run tree-sitter corpus tests"

this_script=$(readlink -f "$0")
this_script_dir=$(dirname "$this_script")
this_script_name=$(basename "$this_script")

# shellcheck source=.common
. "$this_script_dir/.common"

########################################################################

cur_dir=$(pwd)

deprintf "%s: start\n" "$this_script_name"

cd "$ATSP_LANG_ROOT" || exit 1

########################################################################

# SO_INSTALL_PATH is necessary
cmd="make -f $ATSP_DATA/Makefile corpus-test"
# XXX: useful for debugging
#cmd="make --debug=a -f $ATSP_DATA/Makefile corpus-test"

deprintf "* Invoking:\n"
deprintf "    %s\n" "$cmd"

eval "$cmd"
result=$?

if [ 0 -ne "$result" ]; then
  eprintf "* Testing failed: %s.\n" "$result"
  eprintf "%s: abort\n" "$this_script_name"
  exit 1
fi

########################################################################

cd "$cur_dir" || exit 1

deprintf "%s: end\n" "$this_script_name"
