#! /bin/sh

# shellcheck disable=SC2034
THIS_SCRIPT_DESC="Run tree-sitter corpus tests"

THIS_SCRIPT=$(readlink -f "$0")
THIS_SCRIPT_DIR=$(dirname "$THIS_SCRIPT")

# shellcheck source=.common
. "${THIS_SCRIPT_DIR}/.common"

########################################################################

cur_dir=$(pwd)

deprintf "Working on running tree-sitter corpus tests.\n"

cd "${PARSER_PROJ_DIR}" || exit 1

deprintf "\n"

# XXX: is this really what should be checked for?
if [ -f src/parser.c ]; then
  deprintf "* Found src/parser.c, running corpus tests.\n"
else
  eprintf "* Failed to find src/parser.c...exiting\n"
  exit 1;
fi

deprintf "* Invoking tree-sitter test subcommand\n"

# XXX: is this a broken way to do things?
if [ "" != "${TREE_SITTER_DIR}" ]; then
  export TREE_SITTER_DIR="${TREE_SITTER_DIR}"
fi

# XXX: is this a broken way to do things?
if [ "" != "${TREE_SITTER_LIBDIR}" ]; then
  export TREE_SITTER_LIBDIR="${TREE_SITTER_LIBDIR}"
fi

${ATSP_TS_PATH} test

deprintf "\n"

cd "${cur_dir}" || exit 1

deprintf "Done\n"
