#! /bin/sh

# shellcheck disable=SC2034
this_script_desc="Create tree-sitter config.json if needed"

this_script=$(readlink -f "$0")
this_script_dir=$(dirname "$this_script")
this_script_name=$(basename "$this_script")

# shellcheck source=.common
. "$this_script_dir/.common"

########################################################################

cur_dir=$(pwd)

deprintf "%s: start\n" "$this_script_name"

cd "$PARSER_PROJ_DIR" || exit 1

########################################################################

config_json="$TREE_SITTER_DIR"/config.json

if [ ! -e "$config_json" ]; then
  deprintf "* Creating config.json under:\n    %s\n" "$TREE_SITTER_DIR/"

  mkdir -p "$TREE_SITTER_DIR"

  cat << EOF > "$config_json"
{
  "parser-directories": [
    "."
  ],
  "theme": {
    "number": {
      "color": 94,
      "bold": true
    },
    "string.special": 30,
    "keyword": 56,
    "operator": {
      "bold": true,
      "color": 239
    },
    "module": 136,
    "variable.builtin": {
      "bold": true
    },
    "type.builtin": {
      "color": 23,
      "bold": true
    },
    "type": 23,
    "constant": 94,
    "punctuation.delimiter": 239,
    "tag": 18,
    "string": 28,
    "embedded": null,
    "variable.parameter": {
      "underline": true
    },
    "comment": {
      "color": 245,
      "italic": true
    },
    "attribute": {
      "color": 124,
      "italic": true
    },
    "constructor": 136,
    "function.builtin": {
      "bold": true,
      "color": 26
    },
    "property": 124,
    "constant.builtin": {
      "color": 94,
      "bold": true
    },
    "punctuation.bracket": 239,
    "function": 26
  }
}
EOF
else
  eprintf "The file config.json already exists under:\n  %s\n" \
          "$TREE_SITTER_DIR/"
  exit 1
fi

########################################################################

cd "$cur_dir" || exit 1

deprintf "%s: end\n" "$this_script_name"
