#! /bin/sh

# shellcheck disable=SC2034
this_script_desc="Generate grammar source under src"

this_script=$(readlink -f "$0")
this_script_dir=$(dirname "$this_script")
this_script_name=$(basename "$this_script")

# shellcheck source=.common
. "$this_script_dir/.common"

########################################################################

cur_dir=$(pwd)

deprintf "%s: start\n" "$this_script_name"

cd "$ATSP_LANG_ROOT" || exit 1

########################################################################

deprintf "* Looking for grammar.js.\n"

if [ -f grammar.js ]; then
  deprintf "* Found.\n"
else
  eprintf "* Failed to find.\n"
  eprintf "%s: abort\n" "$this_script_name"
  exit 1
fi

abi=${ATSP_ABI:-$("$ATSP_UTIL"/atsp-abi)}

# XXX: tree-sitter creates src directory if necessary so
#      not necessary for this script to check for it?

cmd="$ATSP_TS_PATH generate --abi $abi --no-bindings"

deprintf "* Invoking:\n"
deprintf "    %s\n" "$cmd"

eval "$cmd"
result=$?

if [ 0 -ne "$result" ]; then
  eprintf "* Generating source failed: %s.\n" "$result"
  eprintf "%s: abort\n" "$this_script_name"
  exit 1
fi

########################################################################

cd "$cur_dir" || exit 1

deprintf "%s: end\n" "$this_script_name"
