#! /bin/sh

# shellcheck disable=SC2034
THIS_SCRIPT_DESC="Generate grammar source under src"

THIS_SCRIPT=$(readlink -f "$0")
THIS_SCRIPT_DIR=$(dirname "$THIS_SCRIPT")

# shellcheck source=.common
. "${THIS_SCRIPT_DIR}/.common"

########################################################################

cur_dir=$(pwd)

cd "${PARSER_PROJ_DIR}" || exit 1

if [ -f grammar.js ]; then
  printf "Found grammar.js, generating src/parser.c and friends.\n"
else
  printf "Failed to find grammar.js...exiting\n"
  exit 1;
fi

printf "* Invoking tree-sitter generate subcommand\n"

ts_abi=${ATSP_ABI:-$("${ATSP_UTIL}"/abi)}

# XXX: tree-sitter creates src directory if necessary so
#      not necessary for this script to check for it?

${TS_PATH} generate --abi "${ts_abi}" --no-bindings

cd "${cur_dir}" || exit 1

printf "Done\n"
