#! /bin/sh

# shellcheck disable=SC2034
THIS_SCRIPT_DESC="Install grammar's shared object"

THIS_SCRIPT=$(readlink -f "$0")
THIS_SCRIPT_DIR=$(dirname "$THIS_SCRIPT")
THIS_SCRIPT_NAME=$(basename "$THIS_SCRIPT")

# shellcheck source=.common
. "${THIS_SCRIPT_DIR}/.common"

########################################################################

cur_dir=$(pwd)

deprintf "Working on installing shared object.\n"

cd "${PARSER_PROJ_DIR}" || exit 1

deprintf "\n"

so_name=$("${ATSP_UTIL}"/so-name)
so_path=${BUILD_DIR_PATH}/${so_name}

deprintf "* Looking for built shared object at:\n"

deprintf "    %s\n" "${so_path}"

if [ -f "${so_path}" ]; then
  deprintf "* Found it.\n"
else
  deprintf "* Failed to find shared object...attempting to build.\n"

  "${THIS_SCRIPT_DIR}"/build-so
  result=$?

  if [ 0 -eq "${result}" ]; then
    deprintf "* Continuing with %s.\n" "${THIS_SCRIPT_NAME}"
  else
    eprintf "* Aborting %s\n" "${THIS_SCRIPT_NAME}"
    exit 1
  fi
fi

deprintf "* Ensuring shared object install directory exists at:\n"

deprintf "    %s\n" "${SO_INSTALL_DIR}"

mkdir -p "${SO_INSTALL_DIR}"

deprintf "* Copying shared object into place\n"

cp "$so_path" "${SO_INSTALL_DIR}"

deprintf "  * so name: %s\n" "${so_name}"
deprintf "  *  source: %s\n" "${BUILD_DIR_PATH}/"
deprintf "  *    dest: %s\n" "${SO_INSTALL_DIR}/"

deprintf "\n"

cd "${cur_dir}" || exit 1

deprintf "Done\n"
