#! /bin/sh

# shellcheck disable=SC2034
THIS_SCRIPT_DESC="Install grammar's shared object"

THIS_SCRIPT=$(readlink -f "$0")
THIS_SCRIPT_DIR=$(dirname "$THIS_SCRIPT")

# shellcheck source=.common
. "${THIS_SCRIPT_DIR}/.common"

########################################################################

cur_dir=$(pwd)

cd "${PARSER_PROJ_DIR}" || exit 1

so_name=$("${ATSP_UTIL}"/so-name)

if [ -f "${BUILD_DIR_PATH}/${so_name}" ]; then
  printf "Found shared object, installing.\n"
else
  printf "Failed to find shared object...exiting\n"
  exit 1;
fi

mkdir -p "${SO_INSTALL_DIR}"

printf "* Copying shared object into place\n"

cp "${BUILD_DIR_PATH}/${so_name}" "${SO_INSTALL_DIR}"

printf "  * so name: %s\n" "${so_name}"
printf "  *  source: %s\n" "${BUILD_DIR_PATH}/"
printf "  *    dest: %s\n" "${SO_INSTALL_DIR}/"

cd "${cur_dir}" || exit 1

printf "Done\n"
