#! /bin/sh

# shellcheck disable=SC2034
this_script_desc="List tasks"

this_script=$(readlink -f "$0")
this_script_dir=$(dirname "$this_script")
this_script_name=$(basename "$this_script")

# shellcheck source=.common
. "$this_script_dir/.common"

########################################################################

cur_dir=$(pwd)

deprintf "%s: start\n" "$this_script_name"

cd "$PARSER_PROJ_DIR" || exit 1

########################################################################

# n.b. this is literal, not globbed
tasks="$this_script_dir/*"

# determine max length of script names for readability
max_len=0

for task in $tasks
do
  cur_len=${#task}

  if [ "$cur_len" -gt "$max_len" ]; then
    max_len="$cur_len"
  fi
done

deprintf "* Longest task name length is: %s\n" "$max_len"

deprintf "* Listing available tasks\n"

cnt=0

# .common is skipped because its name starts with a dot
for task in $tasks # XXX: sad to be looping again...
do
  just_name="$(basename "$task")"

  desc=$(grep -m 1 this_script_desc "$task" | \
         sed 's/^this_script_desc="\(.*\)"/\1/')

  # if a task has a description, list it
  if [ "" != "$desc" ]; then
    pad_len=$((max_len - ${#task} + 1))

    printf "%s %*s %s\n" \
           "$just_name" \
           "$pad_len" \
           " " \
           "$desc"
    cnt=$((cnt + 1))
  fi
done

deprintf "* Number of tasks detected: %s\n" "$cnt"

########################################################################

cd "$cur_dir" || exit 1

deprintf "%s: end\n" "$this_script_name"
