#! /bin/sh

# shellcheck disable=SC2034
THIS_SCRIPT_DESC="Start tree-sitter playground"

THIS_SCRIPT=$(readlink -f "$0")
THIS_SCRIPT_DIR=$(dirname "$THIS_SCRIPT")
THIS_SCRIPT_NAME=$(basename "$THIS_SCRIPT")

# shellcheck source=.common
. "${THIS_SCRIPT_DIR}/.common"

########################################################################

# this is here because it seems that to stop tree-sitter playground a
# user is likely to press control-c.  resuming after doesn't appear to
# happen otherwise.  that might lead to an incorrect current working
# directory.

trap cleanup INT

cleanup () {
  eprintf "\nLikely trapped Control-C\n"
}

########################################################################

cur_dir=$(pwd)

cd "${PARSER_PROJ_DIR}" || exit 1

deprintf "Working on starting playground.\n"

deprintf "\n"

parser_wasm=$("${ATSP_UTIL}"/wasm-name)
parser_wasm_path=${PARSER_PROJ_DIR}/${parser_wasm}

deprintf "* Expecting parser wasm at:\n"

deprintf "    %s\n" "${parser_wasm_path}"

if [ -f "${parser_wasm_path}" ]; then
  deprintf "* Found it.\n"
else
    deprintf "* Failed to find parser wasm...attempting to build.\n"

  "${THIS_SCRIPT_DIR}"/build-wasm
  result=$?

  if [ 0 -eq "${result}" ]; then
    deprintf "* Continuing with %s.\n" "${THIS_SCRIPT_NAME}"
  else
    eprintf "* Aborting %s\n" "${THIS_SCRIPT_NAME}"
    exit 1
  fi
fi

deprintf "* Invoking tree-sitter playground subcommand\n"

${ATSP_TS_PATH} playground

cd "${cur_dir}" || exit 1

deprintf "\n"

deprintf "Done\n"
