#! /bin/sh

# shellcheck disable=SC2034
THIS_SCRIPT_DESC="Start tree-sitter playground"

THIS_SCRIPT=$(readlink -f "$0")
THIS_SCRIPT_DIR=$(dirname "$THIS_SCRIPT")

# shellcheck source=.common
. "${THIS_SCRIPT_DIR}/.common"

########################################################################

# this is here because it seems that to stop tree-sitter playground a
# user is likely to press control-c.  resuming after doesn't appear to
# happen otherwise.  that might lead to an incorrect current working
# directory.

trap cleanup INT

cleanup () {
  printf "\nLikely trapped Control-C\n"
}

########################################################################

CUR_DIR=$(pwd)

cd "${PARSER_PROJ_DIR}" || exit 1

PARSER_WASM=$("${ATSP_UTIL}"/wasm-name)
PARSER_WASM_PATH=${PARSER_PROJ_DIR}/${PARSER_WASM}

if [ -f "${PARSER_WASM_PATH}" ]; then
  printf "Found %s, starting playground.\n" "${PARSER_WASM}"
else
  printf "Failed to find %s...exiting\n" "${PARSER_WASM}"
  exit 1;
fi

printf "* Invoking tree-sitter playground subcommand\n"

${TS_PATH} playground

cd "${CUR_DIR}" || exit 1

printf "Done\n"
