#! /bin/sh

# shellcheck disable=SC2034
THIS_SCRIPT_DESC="Uninstall grammar's shared object"

THIS_SCRIPT=$(readlink -f "$0")
THIS_SCRIPT_DIR=$(dirname "$THIS_SCRIPT")
THIS_SCRIPT_NAME=$(basename "$THIS_SCRIPT")

# shellcheck source=.common
. "$THIS_SCRIPT_DIR/.common"

########################################################################

cur_dir=$(pwd)

deprintf "%s: start\n" "$THIS_SCRIPT_NAME"

cd "$PARSER_PROJ_DIR" || exit 1

########################################################################

deprintf "* Looking for shared object at:\n"
deprintf "    %s\n" "$INSTALLED_SO_PATH"

if [ -f "$INSTALLED_SO_PATH" ]; then
  deprintf "* Found it\n"
else
  eprintf "* Didn't find shared object to uninstall\n"
  deprintf "%s: abort\n" "$THIS_SCRIPT_NAME"
  exit 1
fi

cmd="rm -rf $INSTALLED_SO_PATH"

deprintf "* Invoking:\n"
deprintf "    %s\n" "$cmd"

eval "$cmd"
result=$?

if [ 0 -ne "$result" ]; then
  eprintf "* Uninstallation failed: %s.\n" "$result"
  deprintf "%s: abort\n" "$THIS_SCRIPT_NAME"
  exit 1
fi

########################################################################

cd "$cur_dir" || exit 1

deprintf "%s: end\n" "$THIS_SCRIPT_NAME"
