#! /bin/sh

# shellcheck disable=SC2034
this_script_desc="Uninstall grammar's shared object"

this_script=$(readlink -f "$0")
this_script_dir=$(dirname "$this_script")
this_script_name=$(basename "$this_script")

# shellcheck source=.common
. "$this_script_dir/.common"

########################################################################

cur_dir=$(pwd)

deprintf "%s: start\n" "$this_script_name"

cd "$ATSP_LANG_ROOT" || exit 1

########################################################################

deprintf "* Looking for shared object:\n"
deprintf "    %s\n" "$SO_INSTALL_PATH"

if [ -f "$SO_INSTALL_PATH" ]; then
  deprintf "* Found.\n"
else
  eprintf "* Didn't find shared object to uninstall.\n"
  deprintf "%s: abort\n" "$this_script_name"
  exit 1
fi

cmd="rm -rf $SO_INSTALL_PATH"

deprintf "* Invoking:\n"
deprintf "    %s\n" "$cmd"

eval "$cmd"
result=$?

if [ 0 -ne "$result" ]; then
  eprintf "* Uninstallation failed: %s.\n" "$result"
  deprintf "%s: abort\n" "$this_script_name"
  exit 1
fi

########################################################################

cd "$cur_dir" || exit 1

deprintf "%s: end\n" "$this_script_name"
