#! /usr/bin/env bash

# XXX: currently assumes this file is source-ed from
#      grammar repository directory.  thus THIS_SCRIPT_DIR
#      should end up as the root of the grammar repository
#      (though see the weirdness of THIS_SCRIPT described
#      below)

_task_names() {
  # XXX: produces a funny path ending with bash (or other shell name?)
  THIS_SCRIPT=$(readlink -f "$0")
  # XXX: produces a path that's the invoking path
  THIS_SCRIPT_DIR=$(dirname "$THIS_SCRIPT")

  if [ ! -d "${THIS_SCRIPT_DIR}/.atsp" ]; then
    #printf "Not in an appropriate place"
    return;
  fi

  # XXX: try to improve the way the path is expressed here
  #
  # n.b. this is literal, not globbed
  tasks="${THIS_SCRIPT_DIR}/.atsp/task/*"

  task_names=

  for task in ${tasks}
  do
    task_names="${task_names} $(basename "${task}")"
  done

  COMPREPLY=($(compgen -W "${task_names}" "${COMP_WORDS[1]}"))
}

complete -F _task_names atsp
