#! /bin/sh

# XXX: run this from the directory this is in

# shellcheck disable=SC2034
THIS_SCRIPT_DESC="Setup atsp"

THIS_SCRIPT=$(readlink -f "$0")
THIS_SCRIPT_DIR=$(dirname "$THIS_SCRIPT")

printf "%s\n" "${THIS_SCRIPT}"

# XXX: one-time...should the name be lower case?
PARSER_PROJ_DIR=$(realpath ..)

########################################################################

cur_dir=$(pwd)

cd "${PARSER_PROJ_DIR}" || exit 1

grammar_js_line=$(grep '^\s*name:\s*' "${PARSER_PROJ_DIR}"/grammar.js)

guess=$(echo "${grammar_js_line}" | \
        sed "s/\s*name:\s*'\([^']\+\)',/\1/")

#printf "1: %s\n" "${guess}"

if [ "${grammar_js_line}" != "${guess}" ]; then
  atsp_lang_guess="${guess}"
else
  guess=$(echo "${grammar_js_line}" | \
          sed 's/\s*name:\s*"\([^"]\+\)",/\1/')
fi

#printf "2: %s\n" "${guess}"

if [ "${grammar_js_line}" != "${guess}" ]; then
  atsp_lang_guess="${guess}"
else
  atsp_lang_guess=$(basename "${PARSER_PROJ_DIR}" | \
                    sed 's/tree-sitter-//' | \
                    sed 's/\([^\.]\+\).*/\1/')
fi

#printf "3: %s\n" "${atsp_lang_guess}"

# just needs to be a string which should not be the same as a guess
scan=no!

while [ "${guess}" != "${scan}" ]
do
  printf "Please enter a language name [%s]: " "${atsp_lang_guess}"

  read -r guess

  guess=${guess:-"${atsp_lang_guess}"}

  # XXX: improve consistency check -- c identifier chars and - are ok?
  scan=$(echo "${guess}" | sed 's/[^_a-zA-Z0-9-]//')

  printf "\n"

  if [ "${guess}" != "${scan}" ]; then
      printf "Please don't use anything other than: a-z, A-Z, _, and -.\n\n"
  fi

done

# XXX: too hard-wired?
confpath=$(realpath "${THIS_SCRIPT_DIR}/conf")

printf "Ok, I gathered '%s', please ensure the following line\n" \
       "${guess}"

printf "(or an appropriately corrected version of it):\n"

printf "\n"

printf "ATSP_LANG=%s\n" "${guess}"

printf "\n"

printf "is in a file at:\n"

printf "\n"

printf "  %s\n" "${confpath}"

printf "\n"

cd "${cur_dir}" || exit 1

printf "Done\n"
