#! /bin/sh

THIS_SCRIPT=$(readlink -f "$0")
THIS_SCRIPT_DIR=$(dirname "$THIS_SCRIPT")

########################################################################

so_name=$("${THIS_SCRIPT_DIR}"/so-name)

echo "$1/${so_name}"
