#! /bin/sh

this_script=$(readlink -f "$0")
this_script_dir=$(dirname "$this_script")

########################################################################

so_name=$("$this_script_dir"/so-name)

echo "$1/$so_name"
