#! /bin/sh

this_script=$(readlink -f "$0")
this_script_dir=$(dirname "$this_script")

########################################################################

# xxx: should anything be done about - vs _?
#      wasm-name changes - to _
lang=$("$this_script_dir"/atsp-lang)

so_ext=$("$this_script_dir"/so-ext)

echo "$lang.$so_ext"
