#! /bin/sh

this_script=$(readlink -f "$0")
this_script_dir=$(dirname "$this_script")

########################################################################

lang=$("$this_script_dir"/atsp-lang)

underscore_name=$(echo "$lang" | tr '-' '_')

echo tree-sitter-"$underscore_name".wasm
