#! /bin/sh

THIS_SCRIPT=$(readlink -f "$0")
THIS_SCRIPT_DIR=$(dirname "$THIS_SCRIPT")

########################################################################

lang=$("${THIS_SCRIPT_DIR}"/atsp-lang)

underscore_name=$(echo "${lang}" | tr '-' '_')

echo tree-sitter-"${underscore_name}".wasm
